### ISSUE TITLE
win11 - missing runtime dlls

### ISSUE THREAD

**Issue by kcris** [alecmev/cmdcolor#11]
`msvcp120.dll` and `msvcr120.dll` needed to run the binary but not present by default on win11

( must install VC 12? redistributables? )

![image](https://user-images.githubusercontent.com/812733/205413173-a4c17ee0-b66f-4523-935f-bbd3c2748acd.png)

**Comment by kcris** [comment]
here's a binary compiled with vs 17 / vs 2022

[cmdcolor.zip](https://github.com/alecmev/cmdcolor/files/10145233/cmdcolor.zip)

**Comment by kcris** [comment]
and here is one that is statically linked with msvcrt (so no need for external dlls)

[cmdcolor-msvc-static.zip](https://github.com/alecmev/cmdcolor/files/10145302/cmdcolor-msvc-static.zip)

**Comment by kcris** [comment]
see also issue #8

**Comment by kcris** [comment]
closing, 
the statically linked binary above (msvc) should work fine without any external dependencies

**Comment by kcris** [comment]
ps: since win10 (build 1909), no need for this

ansi codes work, see https://ss64.com/nt/syntax-ansi.html

**Comment by alecmev** [comment]
Thanks! Glad to hear that there's actually native support now.
